### ISSUE TITLE
how to add a label for every node ?

### ISSUE THREAD

**Issue by realcarlos** [fkling/JSNetworkX#16]
Hi ,I want to add a string on every node, but with_labels just add the node's name in the circle ,how to make a label beside the circle ? and I also want to set different size for every circle , thank you very much .

**Comment by WilHall** [comment]
For anyone reading this thread and wondering why @fkling 's suggestion isn't working - the option is `labels` not `node_labels` (he mentioned this is an earlier comment but the example is incorrect)

**Comment by fkling** [comment]
@WilHall: :+1:  That's what I get for using inconsistent option names. Corrected example:

```js
var G = jsnx.Graph();
G.add_node(1, {label: 'foo'});
G.add_node(2, {label: 'bar'});
G.add_node(3, {label: 'baz'});
G.add_edges_from([[1,2],[2,3]]);

jsnx.draw(G, {
    element: '#demo-canvas',
    with_labels: true,
    labels: 'label'
});
```

**Comment by neetigyachahar** [comment]
```with-labels``` doesn't work anymore.
```withLabels``` works.
