### ISSUE TITLE
Recompiling with latest version of Closure Library breaks iterators

### ISSUE THREAD

**Issue by Muon** [fkling/JSNetworkX#20]
Hi, I've run into some trouble lately since I had to modify JSNetworkX. Recompiling with the latest version of the Closure Library (or maybe it's the newer Closure Compiler?) seems to cause `.next()` to be obfuscated on all iterators. `Graph.nodes_iter()` and `jsnx.sentinelIterator()` both return fully obfuscated objects. I checked both on my changes and on 031524af019251fcd6fec514cb7f0e14d5dceee7, but got the same result (`.next()` gets renamed to `b`). Any suggestions?

**Comment by fkling** [comment]
It took forever, but v0.3.0 is now released (https://github.com/fkling/JSNetworkX/commit/eff7fb17dca9e68646316460665aee6f10627845). No more Closure Compiler.

**Comment by Muon** [comment]
Yeeeeesssssssssssssss. Finally. Closure Compiler was a nightmare.
