### ISSUE TITLE
sigmajs support

### ISSUE THREAD

**Issue by psychemedia** [fkling/JSNetworkX#22]
How easy would it be to integrate support for the sigmajs visualisation library?

I think the json graph representation that sigma.js accepts matches the one use by the d3.js network layout?

**Comment by fkling** [comment]
Closing this now. `nodes()` and `edges()` provide an easy way to "extract" the graph data. For example, one could do

```js
var data = {
    nodes: G.nodes(),
    edges: G.edges()
};
// Really need JSON?
var json = JSON.stringify(data);
```
