### ISSUE TITLE
Editing Nodes and Edges of graph

### ISSUE THREAD

**Issue by tim-hari** [fkling/JSNetworkX#74]
Hi Peeps,
I want to know how can I dynamically add or remove nodes and edges from the graph by the user events.
Any help would be appreciated.

**Comment by talhajunaidd** [comment]
Duplicate of https://github.com/fkling/JSNetworkX/issues/67
add third add a true option to .draw() to automatically update the graph:
` jsnx.draw(G, options, true)`

**Comment by talhajunaidd** [comment]
Duplicate of https://github.com/fkling/JSNetworkX/issues/67
If you add a true option to .draw(), it'll automatically update the graph.

**Comment by tim-hari** [comment]
> Duplicate of #67
> add third add a true option to .draw() to automatically update the graph:
> `jsnx.draw(G, options, true)`
