### ISSUE TITLE
Load a graph (of 500k nodes) from a file?

### ISSUE THREAD

**Issue by zHaytam** [fkling/JSNetworkX#81]
Hello,

Is there a way to load a graph from a file (of any type)?
It seems weird to execute `addNodeFrom` on all these nodes no?

Also, can JSNetworkX handle this many nodes?

Thank you!

**Comment by mvdandrieux** [comment]
hi ! probably not, as I found this answer when I was looking into it too https://github.com/fkling/JSNetworkX/issues/12
