### ISSUE TITLE
Felix are you still working on this?

### ISSUE THREAD

**Issue by benjamingr** [fkling/JSNetworkX#83]
If you're not, do you intend to?

**Comment by fkling** [comment]
Most likely not. I don't have a need for it myself at the moment and I don't have a lot of time either. Why are you asking?

**Comment by benjamingr** [comment]
I'm using networkx for a project in Testim and I wanted to use this :] Tensorflow.js was surprisingly decent and I was wondering if I could use this instead of the Python

**Comment by fkling** [comment]
I see. I was kind of hoping you want to take over 😉 

Everything that's currently implemented should work fine, but I wouldn't want to use an unmaintained library either...

Sorry 😞
